#############################################################################
# Generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#  May 18, 2020 10:55:38 AM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 601x449+885+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "YTaudio Downloader"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -borderwidth 4 \
        -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 13 -underline 1} \
        -foreground $vTcl(actual_gui_fg) -text {Youtube To Audio Downloader} 
    vTcl:DefineAlias "$top.lab44" "WelcomeText" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Courier New} -size 12} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable URL -width 384 
    vTcl:DefineAlias "$top.ent45" "linkEntry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 \
        -font {-family {Trebuchet MS} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Enter Link} 
    vTcl:DefineAlias "$top.but46" "linkBtn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 \
        -font {-family {Trebuchet MS} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Download 
    vTcl:DefineAlias "$top.but47" "downloadBtn" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Title :} 
    vTcl:DefineAlias "$top.lab48" "audioTitle" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Duration :} 
    vTcl:DefineAlias "$top.lab49" "aduioDuration" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Filesize :} 
    vTcl:DefineAlias "$top.lab50" "fileSize" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Bitrate :} 
    vTcl:DefineAlias "$top.lab52" "bitRate" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -text {Publisher : Nikhil Patil} 
    vTcl:DefineAlias "$top.lab54" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {contact : np52622@gmail.com} 
    vTcl:DefineAlias "$top.lab55" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text { } 
    vTcl:DefineAlias "$top.lab61" "titleValue" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text { } 
    vTcl:DefineAlias "$top.lab62" "durationValue" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab63 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text { } 
    vTcl:DefineAlias "$top.lab63" "filesizeValue" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text { } 
    vTcl:DefineAlias "$top.lab65" "bitrateValue" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text {  } 
    vTcl:DefineAlias "$top.lab66" "speed" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.022 -width 0 -relwidth 0.637 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.201 -width 384 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.767 -y 0 -rely 0.201 -width 96 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.334 -width 106 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.535 -width 0 -relwidth 0.07 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.624 -width 0 -relwidth 0.153 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.713 -width 0 -relwidth 0.137 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.78 -width 0 -relwidth 0.136 \
        -height 0 -relheight 0.125 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.871 -width 0 -relwidth 0.247 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.913 -width 0 -relwidth 0.419 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.116 -y 0 -rely 0.535 -width 0 -relwidth 0.852 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.166 -y 0 -rely 0.624 -width 0 -relwidth 0.419 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.713 -width 0 -relwidth 0.303 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.802 -width 0 -relwidth 0.253 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.423 -width 0 -relwidth 0.17 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

