; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{54BB22F1-AD69-45E0-8C7C-7BCED7D3491B}
AppName=COVID-19 Updates
AppVersion=1.5
;AppVerName=COVID-19 Updates 1.5
AppPublisher=Nikhil Patil
AppPublisherURL=np52622@gmail.com
AppSupportURL=np52622@gmail.com
AppUpdatesURL=np52622@gmail.com
DefaultDirName={autopf}\COVID-19 Updates
DefaultGroupName=COVID-19 Updates
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Nik\OneDrive\Desktop\Coding Stuff\Python\python projects\COVID-19\setup
OutputBaseFilename=COVID setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Nik\OneDrive\Desktop\Coding Stuff\Python\python projects\COVID-19\corona.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Nik\OneDrive\Desktop\Coding Stuff\Python\python projects\COVID-19\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\COVID-19 Updates"; Filename: "{app}\corona.exe"
Name: "{autodesktop}\COVID-19 Updates"; Filename: "{app}\corona.exe"; Tasks: desktopicon   ; IconFilename : "{app}\icon.ico"

[Run]
Filename: "{app}\corona.exe"; Description: "{cm:LaunchProgram,COVID-19 Updates}"; Flags: nowait postinstall skipifsilent

